net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  x_dim: 784
  hidden_dim: 400
  latent_dim: 20

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  dropout: 0.01